name = "digiflazz-tools"
main = "src/index.js"
compatibility_date = "2026-09-26"

[vars]
ACCESS_TEAM_DOMAIN = "lfamilia.cloudflareaccess.com"
ACCESS_AUD = "b315d4e58e3385d017b0cb3455fd706e7b036cb7028f3e4388e5cb5f00ea1921"

[triggers]
crons = ["0 * * * *", "30 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "digiflazz-tools-db"
database_id = "2ccab1ea-425a-40df-b609-b6988bb9fba6"
migrations_dir = "migrations"
