name = "digiflazz-tools"
main = "src/recovery.js"
compatibility_date = "2026-09-26"

[vars]
ACCESS_TEAM_DOMAIN = "lfamilia.cloudflareaccess.com"
ACCESS_AUD = "c5a51d43d0e78e7473ae92453cf9a6b8d9211d69ae51125e0ccbaa84e08474b5"

[triggers]
crons = []

[[d1_databases]]
binding = "DB"
database_name = "digiflazz-tools-db"
database_id = "a0347f78-fc3c-4663-8a9e-3cb501b4118e"
migrations_dir = "migrations"
